<?php
/* vim: set tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * This script is part of the corelib project. The corelib project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 *
 * @author Steffen Soerensen <ss@corelib.org>
 * @copyright Copyright (c) 2005-2008 Steffen Soerensen
 * @license http://www.gnu.org/copyleft/gpl.html
 *
 * @category corelib
 * @package Users
 * @package Authorization
 *
 * @link http://www.corelib.org/
 * @version 1.1.0 ($Id$)
 */

/**
 * UserPermission MySQLi DAO Class.
 *
 * @package AutoGenerated
 * @subpackage user_permission
 */
class MySQLi_UserPermission extends DatabaseDAO implements Singleton,DAO_UserPermission {
	/**
	 * @var MySQLi_UserPermission
	 */
	private static $instance = null;

	/**
	 * @return MySQLi_UserPermission
	 */
	public static function getInstance(){
		if(is_null(self::$instance)){
			self::$instance = new MySQLi_UserPermission();
		}
		return self::$instance;
	}


	//*****************************************************************//
	//************************ Utility methods ************************//
	//*****************************************************************//
	/**
	 * Get select columns.
	 *
	 * return a list of columns to select, this method replaces the
	 * previously constant SELECT_COLUMNS.
	 *
	 * @return string select columns
	 */
	public static function getSelectColumns(){
		$columns = '';
		/* getSelectColumns */
		$columns .= '  `'.UserPermission::FIELD_ID.'`';
		$columns .= ', `'.UserPermission::FIELD_IDENT.'`';
		$columns .= ', `'.UserPermission::FIELD_TITLE.'`';
		$columns .= ', `'.UserPermission::FIELD_DESCRIPTION.'`';
		/* getSelectColumns end */
		return $columns;
	}
	/* Utility methods */
	/**
	 * Get row by ident.
	 *
	 * @param string $ident
	 * @return mixed array similar of read method, else return false
	 */
	public function getByIdent($ident){
		$query = 'SELECT '.$this->getSelectColumns().'
		          FROM `tbl_user_permissions`
		          WHERE `'.UserPermission::FIELD_IDENT.'` = \''.$this->escapeString($ident).'\'';
		$query = $this->slaveQuery(new MySQLiQuery($query));
		if($query->getNumRows() > 0){
			return $query->fetchArray();
		} else {
			return true;
		}
	}

	/**
	 * Check if ident is available..
	 *
	 * @param integer $id
	 * @param string $ident
	 * @return boolean true on success, else return false
	 */
	public function isIdentAvailable($id, $ident){
		$query = 'SELECT `'.UserPermission::FIELD_IDENT.'`
		          FROM `tbl_user_permissions`
		          WHERE `'.UserPermission::FIELD_IDENT.'` = \''.$this->escapeString($ident).'\'';
		if(!is_null($id)){
			$query .= ' AND `pk_user_permissions` != \''.$this->escapeString($id).'\'';
		}
		$query = $this->slaveQuery(new MySQLiQuery($query));
		if($query->getNumRows() > 0){
			return false;
		} else {
			return true;
		}
	}

	/* Utility methods end */


	//*****************************************************************//
	//******************* Data modification methods *******************//
	//*****************************************************************//
	/**
	 * @see DAO_UserPermission::create()
	 */
	public function create(DatabaseDataHandler $data){
		/* Special create fields */
		if(!$this->isIdentAvailable(null, $data->get(UserPermission::FIELD_IDENT))){
			return false;
		}
		/* Special create fields end */

		$columns = $data->getUpdatedColumns();
		$values = $data->getUpdatedColumnValues();

		$query = MySQLiTools::makeInsertStatement('tbl_user_permissions', $columns);
		$query = $this->masterQuery(new MySQLiQueryStatement($query, $values));

		if($id = (int) $query->getInsertID()){
			/* After create actions */
			/* After create actions end */
			return $id;
		} else {
			return false;
		}
	}

	/**
	 * @see DAO_UserPermission::update()
	 */
	public function update($id, DatabaseDataHandler $data){
		/* Special update fields */
		if(($data->isChanged(UserPermission::FIELD_IDENT)) && !$this->isIdentAvailable($id, $data->get(UserPermission::FIELD_IDENT))){
			return false;
		}
		/* Special update fields end */

		$columns = $data->getUpdatedColumns();
		$values = $data->getUpdatedColumnValues();

		$query = MySQLiTools::makeUpdateStatement('tbl_user_permissions', $columns, 'WHERE `'.UserPermission::FIELD_ID.'`=?');

		$query = $this->masterQuery(new MySQLiQueryStatement($query, $values, $id));

		/* After edit actions */
		/* After edit actions end */

		if($query->getAffectedRows() > 0){
			return true;
		} else {
			return false;
		}
	}

	/**
	 * @see DAO_UserPermission::read()
	 */
	public function read($id){
		$query = 'SELECT '.self::getSelectColumns().'
		          FROM `tbl_user_permissions`
		          WHERE `'.UserPermission::FIELD_ID.'`=\''.$id.'\'';
		$query = $this->slaveQuery(new MySQLiQuery($query));

		return $query->fetchArray();
	}

	/**
	 * @see DAO_UserPermission::delete()
	 */
	public function delete($id){
		/* Delete actions */
		/* Delete actions end */

		$query = 'DELETE FROM `tbl_user_permissions`
		          WHERE `'.UserPermission::FIELD_ID.'`=\''.$id.'\'';
		$query = $this->masterQuery(new MySQLiQuery($query));

		if($query->getAffectedRows() > 0){
			return true;
		} else {
			return false;
		}
	}
}
?>