<?php
/* vim: set tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * This script is part of the corelib project. The corelib project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 *
 * @author Steffen Soerensen <ss@corelib.org>
 * @copyright Copyright (c) 2005-2008 Steffen Soerensen
 * @license http://www.gnu.org/copyleft/gpl.html
 * @package AutoGenerated
 * @subpackage user_setting
 * @link http://www.corelib.org/
 * @version 1.1.0 ($Id$)
 * @filesource
 */

/**
 * UserSetting MySQLi DAO Class.
 *
 * @package AutoGenerated
 * @subpackage user_setting
 */
class MySQLi_UserSetting extends DatabaseDAO implements Singleton,DAO_UserSetting {
	/**
	 * @var MySQLi_UserSetting
	 */
	private static $instance = null;

	/**
	 * @return MySQLi_UserSetting
	 */
	public static function getInstance(){
		if(is_null(self::$instance)){
			self::$instance = new MySQLi_UserSetting();
		}
		return self::$instance;
	}


	//*****************************************************************//
	//************************ Utility methods ************************//
	//*****************************************************************//
	/**
	 * Get select columns.
	 *
	 * return a list of columns to select, this method replaces the
	 * previously constant SELECT_COLUMNS.
	 *
	 * @return string select columns
	 */
	public static function getSelectColumns(){
		$columns = '';
		/* getSelectColumns */
		$columns .= '  `'.UserSetting::FIELD_USER.'`';
		$columns .= ', `'.UserSetting::FIELD_IDENT.'`';
		$columns .= ', `'.UserSetting::FIELD_VALUE.'`';
		/* getSelectColumns end */
		return $columns;
	}
	/* Utility methods */
	/* Utility methods end */


	//*****************************************************************//
	//******************* Data modification methods *******************//
	//*****************************************************************//
	/**
	 * @see DAO_UserSetting::update()
	 */
	public function update($user, $ident, DatabaseDataHandler $data){
		/* Special update fields */
		$data->addExcludeField(UserSetting::FIELD_USER);
		$data->addExcludeField(UserSetting::FIELD_IDENT);
		/* Special update fields end */

		$columns = $data->getUpdatedColumns();
		$values = $data->getUpdatedColumnValues();

		/* Special create fields */
		$data->removeExcludeField(UserSetting::FIELD_USER);
		$data->removeExcludeField(UserSetting::FIELD_IDENT);
		/* Special create fields end */
		
		$columns_create = $data->getUpdatedColumns();
		$values_create = $data->getUpdatedColumnValues();
		
		$query = MySQLiTools::makeInsertStatement('tbl_user_settings', $columns_create, 'ON DUPLICATE KEY UPDATE '.MySQLiTools::makeUpdateColumns($columns));

		$query = $this->masterQuery(new MySQLiQueryStatement($query, $values_create, $user, $ident, $values));

		/* After edit actions */
		/* After edit actions end */

		if($query->getAffectedRows() > 0){
			return true;
		} else {
			return false;
		}
	}

	/**
	 * @see DAO_UserSetting::read()
	 */
	public function read($user, $ident){
		$query = 'SELECT '.self::getSelectColumns().'
		          FROM `tbl_user_settings`
		          WHERE `'.UserSetting::FIELD_USER.'` = \''.$this->escapeString($user).'\' AND `'.UserSetting::FIELD_IDENT.'` = \''.$this->escapeString($ident).'\'';
		$query = $this->slaveQuery(new MySQLiQuery($query));

		return $query->fetchArray();
	}

	/**
	 * @see DAO_UserSetting::delete()
	 */
	public function delete($user, $ident){
		/* Delete actions */
		/* Delete actions end */

		$query = 'DELETE FROM `tbl_user_settings`
		          WHERE `'.UserSetting::FIELD_USER.'` = \''.$this->escapeString($user).'\' AND `'.UserSetting::FIELD_IDENT.'` = \''.$this->escapeString($ident).'\'';
		$query = $this->masterQuery(new MySQLiQuery($query));

		if($query->getAffectedRows() > 0){
			return true;
		} else {
			return false;
		}
	}
}
?>