<?php
/* vim: set tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * Get handler for ${submodulename}.
 *
 * This script is part of the corelib project. The corelib project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 *
 * @author Steffen Soerensen <ss@corelib.org>
 * @copyright Copyright (c) 2005-2008 Steffen Soerensen
 * @license http://www.gnu.org/copyleft/gpl.html
 * @package AutoGenerated
 * @subpackage User
 * @link http://www.corelib.org/
 * @version 1.0.0 ($Id$)
 */

/**
 * @ignore
 */
class WebPage extends ManagerPage {
	/* Interface post methods */
	public function edit($id){
		$input = InputHandler::getInstance();
		$user = new User($id);
		if($this->_validateUserInput($user, 'username', 'password', 'email', 'activated')){
			$user->commit();
			$this->post->setLocation('corelib/extensions/Users/');
		} else {
			$this->post->setLocation('corelib/extensions/Users/'.$id.'/edit/?error', $input->serializePost());
		}
	}

	public function create(){
		$input = InputHandler::getInstance();
		$user = new User();
		if($this->_validateUserInput($user, 'username', 'password', 'email', 'activated')){
			$user->commit();
			$this->post->setLocation('corelib/extensions/Users/');
		} else {
			$this->post->setLocation('corelib/extensions/Users/create/?error', $input->serializePost());
		}
	}

	/* Interface post methods end */


	private function _validateUserInput(User $user /*, [$variables...] */){
		$input = InputHandler::getInstance();
		$checkvalid = func_get_args();
		array_shift($checkvalid);

		/* Interface post validation */
		if($input->validatePost('username', new InputValidatorNotEmpty())){
			if(!$user->isUsernameAvailable($input->getPost('username'))){
				$input->unValidatePost('username');
				$input->setPostErrorCode('username', 1);
			}
		}
		if($input->validatePost('email', new InputValidatorEmail())){
			if(!$user->isEmailAvailable($input->getPost('email'))){
				$input->unValidatePost('email');
				$input->setPostErrorCode('email', 1);
			}
		}
		$input->validatePost('password', new InputValidatorNotEmpty());
		if($input->isValidPost('password')){
			$input->validatePost('password-confirm', new InputValidatorEquals($input->getPost('password')));
		} else if((!is_null($user->getID())) && $input->validatePost('password', new InputValidatorEmpty())){
			$input->validatePost('password-confirm', new InputValidatorEmpty());
		}

		$input->validatePost('activated', new InputValidatorEnum('true','false'));
		$input->validatePost('activation-string', new InputValidatorNotEmpty());
		$input->validatePost('deleted', new InputValidatorEnum('true','false'));
		$input->validatePost('last-timestamp', new InputValidatorRegex('//') /* Timestamp validation */);
		/* Interface post validation end */

		$input->addStripSerializePostVariable('password');
		$input->addStripSerializePostVariable('password-confirm');

		if($input->isValidPostVariables($checkvalid)){
			/* Interface actions */
			if($input->isValidPost('username')){
				$user->setUsername($input->getPost('username'));
			}
			if($input->isValidPost('password') && $input->getPost('password') != ''){
				$user->setPassword($input->getPost('password'));
			}
			if($input->isValidPost('email')){
				$user->setEmail($input->getPost('email'));
			}
			if($input->isValidPost('activated')){
				if($input->getPost('activated') == 'true'){
					$user->setActivated(true);
				} else {
					$user->setActivated(false);
				}
			}
			if($input->isValidPost('activation-string')){
				$user->setActivationString($input->getPost('activation-string'));
			}
			if($input->isValidPost('deleted')){
				$user->setDeleted($input->getPost('deleted'));
			}
			if($input->isValidPost('last-timestamp')){
				$user->setLastTimestamp($input->getPost('last-timestamp'));
			}
			/* Interface actions end */
			return true;
		} else {
			return false;
		}
	}
}
?>
