<?php
/* vim: set tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * This script is part of the corelib project. The corelib project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 *
 * @author Steffen Soerensen <ss@corelib.org>
 * @copyright Copyright (c) 2005-2008 Steffen Soerensen
 * @license http://www.gnu.org/copyleft/gpl.html
 * @package AutoGenerated
 * @subpackage user_setting
 * @link http://www.corelib.org/
 * @version 1.1.0 ($Id$)
 * @filesource
 */


//*****************************************************************//
//************************* DAO Interface *************************//
//*****************************************************************//
/**
 * DAO interface for UserSettingList.
 *
 * @package AutoGenerated
 * @subpackage user_setting
 */
interface DAO_UserSettingList {
	/**
	 * Get the list according to the current criteria.
	 *
	 * @param DatabaseListHelperFilter $filter
	 * @param DatabaseListHelperOrder $order
	 * @param integer $offset
	 * @param integer $limit
	 * @param UserSettingList $view
	 * @return Query
	 */
	public function getList(DatabaseListHelperFilter $filter, DatabaseListHelperOrder $order, $offset=null, $limit=null, $view=null);

	/**
	 * Count the number of objects according to the current listing criteria.
	 *
	 * @param DatabaseListHelperFilter $filter
	 * @return integer number of objects in the list
	 */
	public function getListCount(DatabaseListHelperFilter $filter);
}


//*****************************************************************//
//************************ Model list class ***********************//
//*****************************************************************//
/**
 * UserSetting model list.
 *
 * @package AutoGenerated
 * @subpackage user_setting
 */
class UserSettingList implements Output,CacheableOutput {

	//*****************************************************************//
	//**************************** Properties *************************//
	//*****************************************************************//
	/**
	 * @var DAO_UserSettingList
	 * @internal
	 */
	private $dao = null;

	/* Converter properties */
	/* Converter properties end */

	/**
	 * @var DatabaseListHelperOrder
	 */
	protected $order = null;

	/**
	 * @var DatabaseListHelperFilter
	 */
	protected $filter = null;

	/**
	 * @var CacheManagerOutput
	 */
	protected $cache = null;

	/**
	 * @var UserSettingList
	 * @internal
	 */
	private $view = null;

	/**
	 * @var boolean
	 * @internal
	 */
	private $paging = false;
	/**
	 * @var integer current page
	 */
	private $paging_page = 1;

	/**
	 * @var integer
	 */
	private $limit = null;
	/**
	 * @var integer
	 * @internal
	 */
	private $offset = null;


	//*****************************************************************//
	//*************************** Constructor *************************//
	//*****************************************************************//
	/**
	 * Create new UserSettingList instance.
	 *
	 * @uses UserSettingList::$order
	 * @uses UserSettingList::$filter
	 * @return void
	 */
	public function __construct(){
		$this->order = new DatabaseListHelperOrder();
		$this->filter = new DatabaseListHelperFilter();
	}

	//*****************************************************************//
	//************************* Filter methods ************************//
	//*****************************************************************//
	/* Filter methods */
	public function setUserFilter(User $user){
		$this->filter->set(UserSetting::FIELD_USER, $user->getID());
	}
	/* Filter methods end */


	//*****************************************************************//
	//************************** Order methods ************************//
	//*****************************************************************//
	/* Order methods */
	/* Order methods end */


	//*****************************************************************//
	//********************* Converter set methods *********************//
	//*****************************************************************//
	/* Converter methods */
	/* Converter methods end */


	//*****************************************************************//
	//************************** View handling ************************//
	//*****************************************************************//
	/**
	 * Set model view list.
	 *
	 * @uses UserSettingList::$view
	 * @param UserSettingViewList $view
	 */
	public function setView(UserSettingViewList $view){
		$this->view = $view;
	}


	//*****************************************************************//
	//************************ Utility methods ************************//
	//*****************************************************************//
	/**
	 * Set cache manager.
	 *
	 * @uses UserSettingList::$cache
	 * @param CacheManagerOutput $output
	 * @return void
	 */
	public function setCacheManagerOutput(CacheManagerOutput $cache){
		$this->cache = $cache;
	}

	//*****************************************************************//
	//************************ List parameters ************************//
	//*****************************************************************//
	/**
	 * Enable paging and set current page.
	 *
	 * @uses UserSettingList::$paging
	 * @uses UserSettingList::$paging_page
	 * @param integer $page current page
	 */
	public function setPage($page=1){
		$this->paging = true;
		$this->paging_page = $page;
	}

	/**
	 * Set limit.
	 *
	 * If paging is enabled with {@link UserSettingList::setPage()}
	 * the limit is set of the amount of objects on one page. If not
	 * enabled normal limit is used
	 *
	 * @uses UserSettingList::$limit
	 * @param integer $limit
	 */
	public function setLimit($limit){
		$this->limit = $limit;
	}

	/**
	 * Set offset.
	 *
	 * If paging is enabled this has no effect and will be overwritten,
	 * otherwise this set the normal offset
	 *
	 * @uses UserSettingList::$offset
	 * @param integer $offset
	 */
	public function setOffset($offset){
		$this->offset = $offset;
	}

	/**
	 * Count the number of object according to the current listing criteria.
	 *
	 * @uses UserSettingList::_getDao()
	 * @uses UserSettingList::$dao
	 * @uses UserSettingList::$filter
	 * @uses DAO_UserSettingList::getListCount()
	 * @return integer number of objects in the list
	 */
	public function getCount() {
		$this->_getDAO();
		return $this->dao->getListCount($this->filter);
	}


	//*****************************************************************//
	//************************* Output methods ************************//
	//*****************************************************************//
	/**
	 * @see Output::getXML()
	 * @uses UserSettingList::$filter
	 * @uses UserSettingList::$order
	 * @uses UserSettingList::$offset
	 * @uses UserSettingList::$limit
	 * @uses UserSettingList::$paging_page
	 * @uses UserSettingList::$view
	 * @uses UserSettingList::$dao
	 * @uses UserSetting::getXML()
	 * @uses Query::getXML()
	 * @uses DAO_UserSettingList::getList()
	 * @uses UserSettingViewList::getListHelper()
	 * @uses UserSettingViewList::getViewXML()
	 * @uses XMLTools::makePagerXML()
	 * @param DOMDocument $xml
	 * @return DOMElement XML output
	 */
	public function getXML(DOMDocument $xml){
		$this->_getDAO();
		$list = $xml->createElement('user-setting-list');

		if($this->paging){
			$count = $this->getCount();
			$list->setAttribute('count', $count);
			$this->setOffset($this->limit * ($this->paging_page - 1));
			$list->appendChild(XMLTools::makePagerXML($xml, $count, $this->limit, $this->paging_page));
		}

		if(!is_null($this->view)){
			$res = $this->dao->getList($this->filter, $this->order, $this->offset, $this->limit, $this->view->getListHelper());
		} else {
			$res = $this->dao->getList($this->filter, $this->order, $this->offset, $this->limit);
		}

		while ($out = $res->fetchArray()) {
			if(is_null($this->view)){
				$item = new UserSetting($out[UserSetting::FIELD_USER], $out[UserSetting::FIELD_IDENT], $out);

				/* Set converters */
				/* Set converters end */

				$list->appendChild($item->getXML($xml));
			} else {
				$list->appendChild($this->view->getViewXML($out[UserSetting::FIELD_USER], $out[UserSetting::FIELD_IDENT], $out, $xml));
			}
			if(!is_null($this->cache)){
				$this->cache->getCacheManagerOutput($item);
			}
		}
		return $list;
	}

	/**
	 * Iterate over each result.
	 *
	 * @uses UserSettingList::_getDAO()
	 * @uses UserSettingList::$dao
	 * @uses DAO_UserSettingList::getList()
	 * @uses UserSettingList::$filter
	 * @uses UserSettingList::$order
	 * @uses UserSettingList::$offset
	 * @uses UserSettingList::$limit
	 * @uses Query::dataSeek()
	 * @return UserSetting
	 */
	public function each(){
		static $res = null;
		if(is_null($res)){
			$this->_getDAO();
			$res = $this->dao->getList($this->filter, $this->order, $this->offset, $this->limit);
		}
		if($out = $res->fetchArray()){
			$item = new UserSetting($out[UserSetting::FIELD_USER], $out[UserSetting::FIELD_IDENT], $out);
			return $item;
		} else {
			$res->dataSeek(0);
			return false;
		}
	}


	//*****************************************************************//
	//************************ Private methods ************************//
	//*****************************************************************//
	/**
	 * Get Current DAO object instance.
	 *
	 * @uses UserSettingList::$dao
	 * @uses Database::getDAO()
	 * @return boolean true
	 * @internal
	 */
	private function _getDAO(){
		if(is_null($this->dao)){
			$this->dao = Database::getDAO('UserSettingList');
		}
		return true;
	}
}
?>